//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kütüphane_Uygulaması {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    public sealed partial class Settings1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings1 defaultInstance = ((Settings1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings1())));
        
        public static Settings1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Türkçe")]
        public string dil {
            get {
                return ((string)(this["dil"]));
            }
            set {
                this["dil"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Yapıldı_1 {
            get {
                return ((string)(this["Yapıldı_1"]));
            }
            set {
                this["Yapıldı_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yapılmadı")]
        public string Yapılmadı_1 {
            get {
                return ((string)(this["Yapılmadı_1"]));
            }
            set {
                this["Yapılmadı_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Yapıldı_2 {
            get {
                return ((string)(this["Yapıldı_2"]));
            }
            set {
                this["Yapıldı_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yapılmadı")]
        public string Yapılmadı_2 {
            get {
                return ((string)(this["Yapılmadı_2"]));
            }
            set {
                this["Yapılmadı_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Yapıldı_3 {
            get {
                return ((string)(this["Yapıldı_3"]));
            }
            set {
                this["Yapıldı_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yapılmadı")]
        public string Yapılmadı_3 {
            get {
                return ((string)(this["Yapılmadı_3"]));
            }
            set {
                this["Yapılmadı_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Yapıldı_4 {
            get {
                return ((string)(this["Yapıldı_4"]));
            }
            set {
                this["Yapıldı_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yapılmadı")]
        public string Yapılmadı_4 {
            get {
                return ((string)(this["Yapılmadı_4"]));
            }
            set {
                this["Yapılmadı_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Yapıldı_5 {
            get {
                return ((string)(this["Yapıldı_5"]));
            }
            set {
                this["Yapıldı_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yapılmadı")]
        public string Yapılmadı_5 {
            get {
                return ((string)(this["Yapılmadı_5"]));
            }
            set {
                this["Yapılmadı_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Yapıldı_6 {
            get {
                return ((string)(this["Yapıldı_6"]));
            }
            set {
                this["Yapıldı_6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yapılmadı")]
        public string Yapılmadı_6 {
            get {
                return ((string)(this["Yapılmadı_6"]));
            }
            set {
                this["Yapılmadı_6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Yapıldı_7 {
            get {
                return ((string)(this["Yapıldı_7"]));
            }
            set {
                this["Yapıldı_7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yapılmadı")]
        public string Yapılmadı_7 {
            get {
                return ((string)(this["Yapılmadı_7"]));
            }
            set {
                this["Yapılmadı_7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Yapıldı_8 {
            get {
                return ((string)(this["Yapıldı_8"]));
            }
            set {
                this["Yapıldı_8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yapılmadı")]
        public string Yapılmadı_8 {
            get {
                return ((string)(this["Yapılmadı_8"]));
            }
            set {
                this["Yapılmadı_8"] = value;
            }
        }
    }
}
